#!/bin/bash

COUNT=$(ls -1 /dev/input/js* 2>/dev/null | wc -l)

if [ "$COUNT" -ge 1 ]; then
    echo "At least one joystick is connected."
    gshortspid=$(pgrep -x gshorts)
    if [ ! -z "$gshortspid" ]; then
        echo gshort already running ..
    else
        nohup gshorts > /dev/null 2>&1 &
    fi
else
    echo "No joystick detected, stopping gshorts."
    gshortspid=$(pgrep -x gshorts)
    kill -9 $gshortspid
fi